### ISSUE TITLE
Error when saving media review

### ISSUE THREAD

**Issue by majora2007** [dentolos19/AniListNet#18]
```
System.Exception: Syntax Error: Unterminated string.
   at AniListNet.AniClient.PostRequestAsync(GqlSelection selection, Boolean isMutation)
   at AniListNet.AniClient.SaveMediaReviewAsync(Int32 mediaId, MediaReviewMutation mutation)
   at KavitaPlus.Features.Scrobbling.AniList.AniListService.UpdateUserStatus(Int32 seriesId, ScrobbleDto dto)
```
for:
```
await _aniClient.SaveMediaReviewAsync(seriesId, new MediaReviewMutation()
                    {
                        IsPrivate = true,
                        Body = dto.ReviewBody,
                        Summary = dto.ReviewTitle
                    });
```

The strings are valid, only have things like `\n` in them.

**Comment by majora2007** [comment]
Here are the actual payloads:
```
Psychology at its best, with marvelous art and a superb plot

Tomodachi Game is a psychological drama that sets up a great mystery from the start and greatly uses the aspect of POV. You never know what is true or untrue. As the reader, you’re constantly left in the unknown, making it highly unpredictable and leaving you baffled whenever there’s a plot twist. I watched episode one of Tomodachi Game and instantly began reading the manga, even though the plot was rather generic with entering a “debt game.” as the story progresses the story, it gets deeper and deeper, so I am glad I decided to read the manga. The story sets you into the action right from the beginning and starts exploring how everything happened. From the very beginning, we’re introduced to a group of friends that seems to have a good bond, but that is constantly being put to test throughout the story. They're forced to enter the game called Tomodachi Game, which is basically Friend’s Game. Here they need to play various games, where they’ll repay their debt if they win and if they lose, they’ll gain additional debt and get a game over. If they win, they'll move on to the next game of the Tomodachi Game.

Overall, I would recommend reading it. 

watched episode one of Tomodachi Game and instantly began reading the manga, even though the plot was rather generic with entering a “debt game.” as the story progresses the story, it gets deeper and deeper, so I am glad I decided to read the manga. The story sets you into the action right from the beginning and starts exploring how everything happened. From the very beginning, we’re introduced to a group of friends that seems to have a good bond, but that is constantly being put to test throughout the story. They're forced to enter the game called Tomodachi Game, which is basically Friend’s Game. Here they need to play various games, where they’ll repay their debt if they win and if they lose, they’ll gain additional debt and get a game over. If they win, they'll move on to the next game of the Tomodachi Game.

watched episode one of Tomodachi Game and instantly began reading the manga, even though the plot was rather generic with entering a “debt game.” as the story progresses the story, it gets deeper and deeper, so I am glad I decided to read the manga. The story sets you into the action right from the beginning and starts exploring how everything happened. From the very beginning, we’re introduced to a group of friends that seems to have a good bond, but that is constantly being put to test throughout the story. They're forced to enter the game called Tomodachi Game, which is basically Friend’s Game. Here they need to play various games, where they’ll repay their debt if they win and if they lose, they’ll gain additional debt and get a game over. If they win, they'll move on to the next game of the Tomodachi Game.
```

and 
```I copied this just to test out the review function!```

**Comment by dentolos19** [comment]
The issue was that the parser didn't know how to parse multi-line strings. I have fixed this issue at [this commit](https://github.com/dentolos19/AniListNet/commit/0246e76e274b53cb0eef474bfe8e93ba002e00d7).
