### ISSUE TITLE
Unhandled exception. AniListNet.AniException: validation

### ISSUE THREAD

**Issue by ElryGH** [dentolos19/AniListNet#20]
I get

```
Unhandled exception. AniListNet.AniException: validation
   at AniListNet.AniClient.PostRequestAsync(GqlSelection selection, Boolean isMutation)
   at AniListNet.AniClient.SaveMediaEntryAsync(Int32 mediaId, MediaEntryMutation mutation)
   at AnilistListConverter.MainWindow.MoveLists(Boolean direction) in C:\Users\pulze\Documents\Github\AnilistListConverter\MainWindow.xaml.cs:line 172
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

when doing this

```
            var results = await aniClient.SearchMediaAsync(filter, new AniPaginationOptions(1, 20));

            if (results.TotalCount > 0)
            {
                foreach (var result in results.Data)
                {
                    int score = Fuzz.Ratio(result.Title.NativeTitle, data.Media.Title.NativeTitle);
                    
                    if (score >= 85)
                    {
                        newID = result.Id;
                        break;
                    }
                }
            }

            await aniClient.DeleteMediaEntryAsync(data.Id);

            var mutation = new MediaEntryMutation
            {
                // Set properties of the mutation object as needed
                Status = MediaEntryStatus.Planning,
                Progress = 0
            };
            
            await aniClient.SaveMediaEntryAsync(newID,mutation);
```

But after your linked Testfile and from documentation this should be the correct ID to the Media and the mutation should be fine too.

I dont get it, if you want you can look trough the code yourself [here](https://github.com/ElryGH/AnilistListConverter/blob/main/MainWindow.xaml.cs), maybe you can see what im doing wrong.

**Comment by ElryGH** [comment]
Ignore the fact that i forgot an else for if (results.TotalCount > 0), doubt that that is the problem

**Comment by ElryGH** [comment]
nope fixing that didnt remove the error.

**Comment by ElryGH** [comment]
This could be part of the problem 
var pagination = new AniPaginationOptions(1, 50000); 
var mediaEntries = await aniClient.GetUserEntriesAsync(user.Id,entryFilter, pagination);
returns only 50 Entires, i have more then 100 Entries in Manga
